export const GET_LIST_ORDER_ITEMS = "GET_LIST_ORDER_ITEMS";
export const ADD_ORDER_ITEM_ITEM = "ADD_ORDER_ITEM_ITEM";
export const UPDATE_ORDER_ITEM = "UPDATE_ORDER_ITEM";
export const DELETE_ORDER_ITEM = "DELETE_ORDER_ITEM";
export const INCREASE_ORDER_ITEM_QUANTITY = "INCREASE_ORDER_ITEM_QUANTITY";
export const DECREASE_ORDER_ITEM_QUANTITY = "DECREASE_ORDER_ITEM_QUANTITY";
