const routes = {
  dashboard: "/dashboard",
  homedashboard: "/home",
  profile: "/profile",
  setting: "/setting",
  customer: "/user/",
  statistics : "/statistics/global",
  auth: {
    login: "/login",
    apiLogin: "/auth/login",
    regiter: "/register",
    apiRegister: "/auth/register",
    forgot: "/forgot",
  },
  user: {
    main_route: "/user-list",
    addUserPage: "/user-form",
    updateUserPage: "/user-form/:id",
    detail: "/user",
    users: "/users",
    addUser: "/user",
    deleteUser: "/user",
    editUser: "/user",
  },
  user_cate: {
    main_route: "/user-cate-list",
    user_cates: "/user-cates",
    addUserCate: "/user-cate",
    deleteUserCate: "/user-cate",
    editUserCate: "/user-cate",
  },
  permission: {
    main_route: "/permission-list",
    permissions: "/user-permissions",
    detail: "/user-permission",
    addPermission: "/user-permission",
    deletePermission: "/user-permission",
    editPermission: "/user-permission",
  },
  post: {
    main_route: "/post-list",
    addPostPage: "/post-form",
    updatePostPage: "/post-form/:id",
    detail: "/post-detail",
    single: "/post",
    posts: "/posts",
    addPost: "/post",
    deletePost: "/post",
    editPost: "/post",
  },
  post_cate: {
    main_route: "/post-cate-list",
    postCates: "/post-cates",
    single: "/post-cate",
    addPostCate: "/post-cate",
    deletePostCate: "/post-cate",
    editPostCate: "/post-cate",
  },
  product: {
    main_route: "/product-list",
    addProductPage: "/product-form",
    single: "/product",
    detail: "/product-detail",
    products: "/products",
    addProduct: "/product",
    deleteProduct: "/product",
    editProduct: "/product",
  },
  product_cate: {
    main_route: "/product-cate-list",
    product_cates: "/product-cates",
    single: "/product-cates",
    addProduct_cate: "/product-cate",
    deleteProduct_cate: "/product-cate",
    editProduct_cate: "/product-cate",
  },
  order: {
    main_route: "/order-list",
    orders: "/orders",
    single: "/order",
    addOrder: "/order",
    deleteOrder: "/order",
    editOrder: "/order",
  },
  order_item: {
    order_items: "/order-items",
    addOrderItem: "/order-item",
    deleteOrderItem: "/order-item",
    editOrderItem: "/order-item",
    single: "/order-item",
  },
  deliver: {
    main_route: "/deliver-list",
    delivers: "/delivers",
    single: "/deliver",
    addDeliver: "/deliver",
    deleteDeliver: "/deliver",
    editDeliver: "/deliver",
  },
  payment: {
    main_route: "/payment-list",
    payments: "/payments",
    single: "/payment",
    addPayment: "/payment",
    deletePayment: "/payment",
    editPayment: "/payment",
  },
  file: {
    main_route: "/media-list",
    files: "/files",
    detail: "/file",
    addfile: "/file",
    addfiles: "/files",
    deletefile: "/file",
    editfile: "/file",
  },
  option: {
    main_route: "/setting",
    options: "/options",
    addoption: "/option",
    deleteoption: "/option",
    editoption: "/option",
  },
};

export default routes;
