export const GET_LIST_ORDERS = "GET_LIST_ORDERS";
export const GET_SINGLE_ORDERS = "GET_SINGLE_ORDERS";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";