export const GET_LIST_PRODUCT_CATE = 'GET_LIST_PRODUCT_CATE';
export const ADD_PRODUCT_CATE = 'ADD_PRODUCT_CATE';
export const UPDATE_PRODUCT_CATE = 'UPDATE_PRODUCT_CATE';
export const DELETE_PRODUCT_CATE = 'DELETE_PRODUCT_CATE';
export const GET_SINGLE_PRODUCT_CATE = 'GET_SINGLE_PRODUCT_CATE';