export const GET_POST = "GET_POST";
export const GET_POSTS = "GET_POSTS";
export const GET_POST_CATEGORY = "GET_POST_CATEGORY";
export const GET_POST_CATEGORIES = "GET_POST_CATEGORIES";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_CATEGORY = "GET_PRODUCTS_CATEGORY";
export const GET_PRODUCTS_CATEGORIES = "GET_PRODUCTS_CATEGORIES";

export const GET_USERS = "GET_USERS";

export const ADD_CART_PRODUCTS = "ADD_CART_PRODUCTS";
export const DELETE_CART_PRODUCTS = "DELETE_CART_PRODUCTS";
export const UPDATE_CART_PRODUCTS = "UPDATE_CART_PRODUCTS";
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export const ADD_ORDER_PRODUCT= "ADD_ORDER_PRODUCT";
export const DELETE_ORDER_PRODUCT = "DELETE_ORDER_PRODUCT";

export const GET_LIST_USER = 'GET_LIST_USER';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_LIST_POST = 'GET_LIST_POST';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';

