export const ADD_CART_PRODUCTS = "ADD_CART_PRODUCTS";
export const DELETE_CART_PRODUCTS = "DELETE_CART_PRODUCTS";
export const UPDATE_CART_PRODUCTS = "UPDATE_CART_PRODUCTS";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";

export const ADD_ORDER_PRODUCT = "ADD_ORDER_PRODUCT";
export const DELETE_ORDER_PRODUCT = "DELETE_ORDER_PRODUCT";
