export const GET_LIST_PRODUCTS = 'GET_LIST_PRODUCTS';
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';