export const GET_LIST_POST_CATES = 'GET_LIST_POST_CATES';
export const ADD_POST_CATE = 'ADD_POST_CATE';
export const UPDATE_POST_CATE = 'UPDATE_POST_CATE';
export const DELETE_POST_CATE = 'DELETE_POST_CATE';
export const GET_SINGLE_POST_CATES = "GET_SINGLE_POST_CATES";