export const GET_LIST_PERMISSIONS = "GET_LIST_PERMISSIONS";
export const GET_DETAIL_PERMISSION = "GET_DETAIL_PERMISSION";
export const ADD_PERMISSION = "ADD_PERMISSION";
export const UPDATE_PERMISSION = "UPDATE_PERMISSION";
export const DELETE_PERMISSION = "DELETE_PERMISSION";


